name: movies
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  json_annotation: ^4.8.1
  path: ^1.8.3
  provider: ^6.0.5
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
